### ISSUE TITLE
Ecran qui liste les Partenaires

### ISSUE THREAD

**Issue by adriens** [adriens/carte-conso-plus-appli#1]
# Description

Via `/partners` présenter une liste avec:

- Nom de l'enseigne (cliquable via `wwwHomePage`, qui ouvre une instance du navigateur)
- Le logo via `logoUrl`

# NB

Pour ce premier ticket, pas d'authetification.

# Démo

Via une video:

1 - Lancer l'appli
2 - Voir apparaître la liste
3 - Cliquer sur les items et voir le navigateur afficher la page cible

**Comment by meilie389** [comment]
![Screenshot_20200327-165149](https://user-images.githubusercontent.com/41884305/77865023-ebbe1880-7277-11ea-8778-b9dba8a97b11.jpg)

**Comment by adriens** [comment]
Stylé. 
Quand je prépareri la release sur Google, faudra virer le debug

**Comment by meilie389** [comment]
![Screenshot_20200403-074826](https://user-images.githubusercontent.com/41884305/78300200-d4867000-7582-11ea-8be9-1e0b26414f8d.jpg)

**Comment by adriens** [comment]
Parfait !
