### ISSUE TITLE
Ecran contact carte Conso

### ISSUE THREAD

**Issue by adriens** [adriens/carte-conso-plus-appli#14]
Présneter de manière compacte et stylée cette page de contact : https://www.consoplus.nc/contact.asp

![image](https://user-images.githubusercontent.com/5235127/78759893-0dcc3f00-79cc-11ea-9b43-eca326368799.png)

![image](https://user-images.githubusercontent.com/5235127/78759933-1a509780-79cc-11ea-9ab3-e01c3d80e3a0.png)

**Comment by adriens** [comment]
Screenshot 🙏 ❔

**Comment by meilie389** [comment]
![flutter_12](https://user-images.githubusercontent.com/41884305/84210599-d7628b80-ab04-11ea-8c0a-b4cd6f3de54b.png)

**Comment by adriens** [comment]
Propo d'évol:

- Rendre le tel cliquable (ça lancerait la composition du num sur le tel pour appeler direct
- Cliquer sur adresse de Kenu In lance l'url : `https://goo.gl/maps/dGvU6wQeLeEDQBwT7`

**Comment by adriens** [comment]
😄

**Comment by adriens** [comment]
👏
