### ISSUE TITLE
Ajouter au lien le site des magazines conso+

### ISSUE THREAD

**Issue by adriens** [adriens/carte-conso-plus-appli#16]
https://www.flipsnack.com/KICOM/

**Comment by adriens** [comment]
J'ai complété le SDK et l'API
https://github.com/adriens/carte-conso-plus-api/issues/33

Les magazines sont désormais dispo depuis l'API

**Noter que les affichages de magazines sont resonvives: ça march pas mal sur tel et vraiment très très très bien sur tablette !!!**

**Comment by adriens** [comment]
Tu pourras choper la cover du mag, le titre et l'url vers le mag dématérialisé 👏

**Comment by meilie389** [comment]
En pause...
L'endpoint des magazines retourne une erreur 500

**Comment by adriens** [comment]
https://github.com/adriens/carte-conso-plus-api/issues/36

**Comment by adriens** [comment]
@meilie389 , dans ce genre de cas, ne pas hésiter à investiguer dans le code de l'API pour par exemple faire un ticket.
EN debugant en local l'api tu aurais pu ainsi trouver pourquoi ça coince.

**Comment by adriens** [comment]
https://github.com/adriens/carte-conso-plus-sdk/issues/28

**Comment by adriens** [comment]
API fixée ✔️

**Comment by meilie389** [comment]
Merci!
Je retiens pour la prochaine fois si il y a un problème, je regarderais mieux.

**Comment by adriens** [comment]
Ils ont changé le format des urls en mai.. ça a causé une régression 😄
