### ISSUE TITLE
Créer un logo

### ISSUE THREAD

**Issue by adriens** [adriens/carte-conso-plus-appli#2]

**Comment by meilie389** [comment]
![logo](https://user-images.githubusercontent.com/41884305/77864887-0e9bfd00-7277-11ea-8e32-ab5bdd3b4423.png)

**Comment by adriens** [comment]
![20200330_111515](https://user-images.githubusercontent.com/5235127/77865016-e234b080-7277-11ea-8a95-a11947e602c3.jpg)

**Comment by adriens** [comment]
Top, comme vu ttà l'heur eensmbels, pensez à jouter CONSO devant le plus 😸

**Comment by meilie389** [comment]
![testlogo](https://user-images.githubusercontent.com/41884305/77874670-68152380-7299-11ea-9594-07f75c6892f3.png)
![test2](https://user-images.githubusercontent.com/41884305/77874667-651a3300-7299-11ea-86a0-eba84c254dfc.png)

**Comment by adriens** [comment]
La version avec tel noir et fond blanc je la trouver super bien lisible 👍

**Comment by adriens** [comment]
Tout le monde adore, bravo.
