### ISSUE TITLE
Splashscreen

### ISSUE THREAD

**Issue by adriens** [adriens/carte-conso-plus-appli#3]
1. Lancer l'appli
2. Voir le splashscreen
3. Voir le premier écran

Démo par fichier video

**Comment by meilie389** [comment]
![Screenshot_20200403-074813](https://user-images.githubusercontent.com/41884305/78300244-e7994000-7582-11ea-91ac-67c9db8394af.jpg)

**Comment by adriens** [comment]
Très stylé, beau boulot 👏
