### ISSUE TITLE
Produire la Hi-res icon (512 x 512)

### ISSUE THREAD

**Issue by adriens** [adriens/carte-conso-plus-appli#34]
![image](https://user-images.githubusercontent.com/5235127/85193457-6301c680-b314-11ea-951f-ca0e8725463c.png)

**Comment by HakumenNC** [comment]
![ic_launcher-playstore](https://user-images.githubusercontent.com/2644417/85366614-752d7000-b573-11ea-8086-839a318fb55b.png)

**Comment by adriens** [comment]
👏  @HakumenNC
