### ISSUE TITLE
Authentification (sans enregistrer les credentials) et écran solde/points

### ISSUE THREAD

**Issue by adriens** [adriens/carte-conso-plus-appli#4]
# Description

1. Lancer l'appli
2. Demander login/mdp
3. Tester l'appel à l'endpoint `/detail`
4. Si OK: router vers l'écran dédié avec les deux champs (solde et phrase de nombre de points, ...)
5. Si KO: Ecran d'erreur avec message adapté et formulaire de saisie login/mdp (compter le nombre de tentatives et l'afficher)

# Démo

Fichier video

**Comment by meilie389** [comment]
![Screenshot_20200403-074818](https://user-images.githubusercontent.com/41884305/78300339-0b5c8600-7583-11ea-8ecb-18928d549381.jpg)
![Screenshot_20200403-074907](https://user-images.githubusercontent.com/41884305/78300355-13b4c100-7583-11ea-9f09-8fcf29bb3868.jpg)

**Comment by meilie389** [comment]
Démo vidéo #4 #6
[https://youtu.be/Evr9sje_PHw](url)

**Comment by adriens** [comment]
YES !

Attention à ne pas fuiter la video sur youtube: elle ne soit psa être indexée. On va avoir un unique canal et je le rpésenterai lros de la release, pas avant.

**Comment by meilie389** [comment]
J'ai mis en non repertoriée, c'est ça ? ou je l'enlève ?

**Comment by adriens** [comment]
C good, sinon le workflow: tu me droppes la video et je la charge sur la chaine

**Comment by adriens** [comment]
Drop la video sr le chan direct

**Comment by meilie389** [comment]
J'ai rien compris ..
