### ISSUE TITLE
Screenshots du MVP

### ISSUE THREAD

**Issue by adriens** [adriens/carte-conso-plus-appli#5]

**Comment by adriens** [comment]
Hello @meilie389 , je vais essayer de préparer une cover et les ressoruces pour le store.
Tu peux me dropper les screenshots sur le ticket stp 🙏 ?

**Comment by meilie389** [comment]
![Screenshot_01_loginScreen_01](https://user-images.githubusercontent.com/41884305/85186925-8f531e00-b2e7-11ea-8cb6-67e7fdad217a.png)
![Screenshot_02_loginScreen_02](https://user-images.githubusercontent.com/41884305/85186926-91b57800-b2e7-11ea-87ff-8979cdd511fc.png)
![Screenshot_03_homeDetail_02](https://user-images.githubusercontent.com/41884305/85186928-9417d200-b2e7-11ea-93c8-119ad538a979.png)
![Screenshot_04_homeDetail_03](https://user-images.githubusercontent.com/41884305/85186929-95e19580-b2e7-11ea-872c-1e2f7f9a5158.png)
![Screenshot_05_homeLatestMag_01](https://user-images.githubusercontent.com/41884305/85186930-9843ef80-b2e7-11ea-93c7-3e4140d05bb5.png)
![Screenshot_06_homeMags_01](https://user-images.githubusercontent.com/41884305/85186934-9a0db300-b2e7-11ea-988a-3db139f439df.png)
![Screenshot_07_homeContacts_01](https://user-images.githubusercontent.com/41884305/85186937-9c700d00-b2e7-11ea-8763-6a138fdf42aa.png)
![Screenshot_08_homePartners_01](https://user-images.githubusercontent.com/41884305/85186938-9da13a00-b2e7-11ea-8df3-7ffe7b38e0a8.png)
![Screenshot_09_homePartners_02](https://user-images.githubusercontent.com/41884305/85186939-9f6afd80-b2e7-11ea-93ca-a551fdc21dc9.png)
![Screenshot_10_aboutContributors_01](https://user-images.githubusercontent.com/41884305/85186941-a09c2a80-b2e7-11ea-8624-2460c3158b0b.png)
![Screenshot_11_aboutInfosApp_01](https://user-images.githubusercontent.com/41884305/85186943-a265ee00-b2e7-11ea-8837-4708050f1377.png)

**Comment by adriens** [comment]
Super @meilie389 , je vais entamer les visuels ! 🚀 
Ptet que @HakumenNC voudra entrer dans la compét, il gère Photoshop le guss ⚡ 👍

**Comment by adriens** [comment]
All good 👏
